name: stipop_sdk
description: A Flutter Plugin that provides integrated Stipop SDK on Android and iOS.
version: 0.9.0-beta.1
homepage: https://stipop.io
repository: https://github.com/stipop-development/stipop-flutter-sdk

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0
  json_serializable: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  effective_dart: ^1.3.2
  build_runner: ^2.1.2

flutter:
  plugin:
    platforms:
      android:
        package: com.stipop.plugin
        pluginClass: StipopPlugin
      ios:
        pluginClass: StipopPlugin

