const PRIMARY_COLOR = 0xFFFF8254;
const APP_BAR_BACKGROUND_COLOR = 0xFFFF681B;
const PERSON_STATUS_COLOR = 0xFFFFB590;

const CHAT_BUBBLE_BACKGROUND_OTHERS = 0xFFFFFFFF;
const CHAT_BUBBLE_BACKGROUND_ME = 0xFFFF681B;

const CHAT_BUBBLE_TEXT_OTHERS = 0xFF6E6E6E;
const CHAT_BUBBLE_TEXT_ME = 0xFFFFFFFF;